// Regenerates src/modalities.ts from the official Command Code CLI package.
//
//   bun scripts/extract-modalities.ts
//
// The listing API (`/provider/v1/models`) returns only id/name/context_length —
// no capability data — so per-model input modalities come from the CLI's own
// model table, which is what ships `inputModalities: ["text","image"]` per
// model. Same source opencode-cmd-provider derives its map from.
//
// Never hand-edit the generated file: models appear and gain vision upstream,
// and this keeps the snapshot honest (like gating.json).
import { writeFile } from "node:fs/promises"

const REGISTRY = "https://registry.npmjs.org/command-code/latest"
const CLI_BUNDLE = (version: string) => `https://unpkg.com/command-code@${version}/dist/cli.mjs`
const OUT = new URL("../src/modalities.ts", import.meta.url).pathname

export type InputModality = "text" | "image" | "audio" | "video" | "pdf"

/**
 * Pull `{ id: "...", inputModalities: ["text","image"] }` records out of the
 * minified bundle. `[^{}]*?` keeps the match inside one object literal, so an
 * unrelated `id` earlier in the file cannot pair with a later modalities list.
 */
export function parseModalities(bundle: string): Record<string, InputModality[]> {
	const out: Record<string, InputModality[]> = {}
	const re = /id:"([^"]+)"[^{}]*?inputModalities:\[([^\]]*)\]/g
	for (const match of bundle.matchAll(re)) {
		const id = match[1]
		if (!id) continue
		const modalities = [...(match[2] ?? "").matchAll(/"([a-z]+)"/g)]
			.map((m) => m[1] as InputModality)
			.filter(Boolean)
		if (modalities.length) out[id] = modalities
	}
	return out
}

/** Only ids whose inputs go beyond text earn a line; the rest are the default. */
export function beyondText(all: Record<string, InputModality[]>): Record<string, InputModality[]> {
	return Object.fromEntries(
		Object.entries(all)
			.filter(([, modalities]) => modalities.some((m) => m !== "text"))
			.sort(([a], [b]) => a.localeCompare(b)),
	)
}

function render(version: string, models: Record<string, InputModality[]>): string {
	const entries = Object.entries(models)
		.map(([id, modalities]) => `\t${JSON.stringify(id)}: [${modalities.map((m) => `"${m}"`).join(", ")}],`)
		.join("\n")
	return `// GENERATED by scripts/extract-modalities.ts — do not edit by hand.
// Source: command-code@${version} (dist/cli.mjs). Regenerate with
// \`bun scripts/extract-modalities.ts\` after a Command Code model release.
//
// The listing API carries no capabilities, so this table is the only per-model
// source. Models absent here are text-only (OpenCode's default).

export type InputModality = "text" | "image" | "audio" | "video" | "pdf"

/** Models whose inputs go beyond text, keyed by the API's model id. */
export const MODEL_INPUT_MODALITIES: Readonly<Record<string, readonly InputModality[]>> = {
${entries}
}

/** Text-only default for any id this table does not list. */
export const TEXT_ONLY: readonly InputModality[] = ["text"]

export function inputModalities(id: string): readonly InputModality[] {
	return MODEL_INPUT_MODALITIES[id] ?? TEXT_ONLY
}

export function supportsImage(id: string): boolean {
	return inputModalities(id).includes("image")
}
`
}

if (import.meta.main) {
	const meta = (await (await fetch(REGISTRY)).json()) as { version?: string }
	const version = meta.version
	if (!version) throw new Error(`no version at ${REGISTRY}`)
	const bundle = await (await fetch(CLI_BUNDLE(version))).text()
	const models = beyondText(parseModalities(bundle))
	const count = Object.keys(models).length
	if (count === 0) throw new Error("parsed no models — CLI bundle shape changed")
	await writeFile(OUT, render(version, models))
	console.log(`wrote src/modalities.ts: ${count} non-text models from command-code@${version}`)
}
