// Extracts Command Code's model-category + plan-gating tables from the installed
// CLI bundle (cli.mjs) and writes src/gating.ts. Run via `bun run extract` after
// every Command Code release that changes the catalog.
//
// ponytail: regex-scrapes a minified bundle — breaks if Command Code renames the
// Fr/Ur/Sr/wr minified vars; upgrade path is pinning a documented endpoint when
// one ships, or re-locating the literals by their stable string anchors below.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

function findCliMjs(): string {
	const roots = [
		join(homedir(), "Library/pnpm"),
		"/usr/lib/node_modules",
		"/usr/local/lib/node_modules",
		join(homedir(), ".npm-global"),
		join(homedir(), ".bun/install/global/node_modules"),
	];
	for (const root of roots) {
		let p = join(root, "command-code/dist/cli.mjs");
		try {
			readFileSync(p);
			return p;
		} catch {}
		// pnpm store layout
		try {
			const links = join(root, "store/v11/links/@/command-code");
			for (const ver of readdirSync(links)) {
				for (const hash of readdirSync(join(links, ver))) {
					p = join(links, ver, hash, "node_modules/command-code/dist/cli.mjs");
					try {
						readFileSync(p);
						return p;
					} catch {}
				}
			}
		} catch {}
	}
	throw new Error("cli.mjs not found — install Command Code CLI (npm i -g command-code)");
}

const src = readFileSync(findCliMjs(), "utf8");

function grab(start: string, end: string): string {
	const i = src.indexOf(start);
	if (i < 0) throw new Error(`anchor not found: ${start}`);
	const j = src.indexOf(end, i);
	if (j < 0) throw new Error(`end anchor not found: ${end}`);
	return src.slice(i + start.length, j);
}

// --- resolve minified identifier values (aliases can shift between releases) ---
const varRe =
	/\b([A-Za-z_$][\w$]*)="(premium|opensource|anthropic|vercel-ai-gateway|openrouter|openai)"/g;
const vars = new Map<string, string>();
for (const m of src.matchAll(varRe)) vars.set(m[1]!, m[2]!);

const lit = (id: string | undefined, fallback: string): string => (id && vars.get(id)) || fallback;

function expand(expr: string): string {
	// $r(X) always = {provider:X, category:"premium"} (single definition in bundle)
	return expr
		.replace(
			/\$r\(([A-Za-z_$][\w$]*)\)/g,
			(_, id) => `{provider:"${lit(id, "anthropic")}",category:"premium"}`,
		)
		.replace(/_r\(\)/g, `{provider:"cai",category:"opensource"}`)
		.replace(/category:([A-Za-z_$][\w$]*)/g, (_, id) => `category:"${lit(id, "opensource")}"`)
		.replace(/provider:([A-Za-z_$][\w$]*)/g, (_, id) => `provider:"${lit(id, "openai")}"`)
		.replace(
			/allowedCategories:\[([^\]]*)\]/g,
			(_, inner: string) =>
				`allowedCategories:[${[...inner.matchAll(/([A-Za-z_$][\w$]*)/g)].map((v) => `"${lit(v[1], "opensource")}"`).join(",")}]`,
		);
}

// --- category table: Fr = { "<model id>": {provider, category} } ---
// getModelCategory looks up Fr DIRECTLY (no canonicalization), so table keys are raw ids
const frRaw = grab("Fr={", "},Ur={");
const categories: Record<string, string> = {};
for (const m of expand(frRaw).matchAll(/"([^"]+)":\{provider:"[^"]*",category:"([^"]+)"\}/g)) {
	categories[m[1]!] = m[2]!;
}

// --- plan table: Ur = { "<planId>": {allowedCategories, blockedModels?} } ---
// plan ids and category values stay as minified var refs (Nr/Dr) until expand below
const urRaw = grab('Ur={"', "},jr=");
const plans: Record<string, { allowedCategories: string[]; blockedModels: string[] }> = {};
for (const m of expand(`{"${urRaw}}`).matchAll(
	/"(individual-[a-z0-9-]+|teams-[a-z0-9-]+)":\{allowedCategories:\[([^\]]*)\](,blockedModels:\[([^\]]*)\])?\}/g,
)) {
	const cats = [...m[2]!.matchAll(/"([a-z]+)"/g)].map((c) => c[1]!);
	const blocked = m[4] ? [...m[4]!.matchAll(/"([^"]+)"/g)].map((b) => b[1]!) : [];
	plans[m[1]!] = { allowedCategories: cats, blockedModels: blocked };
}

// --- known model ids: Sr = new Set([...]) ---
const srRaw = grab('Sr=new Set(["', "])");
const knownFromSet = [...srRaw.matchAll(/"([a-z][^"]*)"/g)]
	.filter((m) => m[1]!.length > 2)
	.map((m) => m[1]!);
// ponytail: KNOWN_MODELS = Set literal ∪ category-table keys; the Set literal
// alone misses models whose spec entries come from spread arrays in the bundle.
const known = [...new Set([...knownFromSet, ...Object.keys(categories)])];

// --- deprecated aliases: wr = { old: new } ---
const wrRaw = grab("wr={", "},vr={");
const aliases: Record<string, string> = {};
for (const m of wrRaw.matchAll(/"([^"]+)":"([^"]+)"/g)) aliases[m[1]!] = m[2]!;

const out = `// GENERATED by scripts/extract-gating.ts — do not edit by hand.
// Source: Command Code CLI bundle (plan-gating + model categories).
// Regen: bun run extract

export const OPEN_SOURCE = "opensource" as const
export const PREMIUM = "premium" as const
export type Category = "opensource" | "premium"

/** model id -> category (models absent from this table have unknown category) */
export const MODEL_CATEGORIES: Record<string, Category> = ${JSON.stringify(categories, null, 2)}

/** planId -> access rules; plan ids absent from this table get everything */
export const PLAN_RULES: Record<string, { allowedCategories: Category[]; blockedModels: string[] }> = ${JSON.stringify(plans, null, 2)}

/** canonical known model ids (lowercase compare) */
export const KNOWN_MODELS: string[] = ${JSON.stringify(known, null, 2)}

/** deprecated/aliased model id -> canonical id */
export const MODEL_ALIASES: Record<string, string> = ${JSON.stringify(aliases, null, 2)}

/** strip a trailing date suffix like -20251101 before aliasing (mirrors CLI kr regex) */
function findKnown(s: string): string | undefined {
  const k = s.toLowerCase()
  return KNOWN_MODELS.find((m) => m.toLowerCase() === k)
}

export function canonicalizeModelId(model: string): string {
  const stripDate = (s: string) => s.replace(/[-@]\\d{8}$/, "")
  const direct = findKnown(model)
  if (direct) return direct
  const aliased = MODEL_ALIASES[model.toLowerCase()]
  if (aliased) return findKnown(aliased) ?? model
  return findKnown(stripDate(model)) ?? model
}
`;
writeFileSync(new URL("../src/gating.ts", import.meta.url), out);
console.log(
	`wrote src/gating.ts: ${Object.keys(categories).length} categories, ${Object.keys(plans).length} plans, ${known.length} known models, ${Object.keys(aliases).length} aliases`,
);
