// GENERATED by scripts/extract-catalog.ts — do not edit by hand.
// Source: command-code@1.65.2 (models.md + dist/cli.mjs). Regenerate with
// `bun scripts/extract-catalog.ts` after a Command Code model release.
//
// The listing API carries neither capabilities nor rates, so this table is the
// only per-model source. Costs are $/1M as published. Models absent here are
// text-only (OpenCode's default); the wire consumes this table only for models
// returned by the live listing.

export type InputModality = "text" | "image" | "audio" | "video" | "pdf"

/** Per-1M-token rates, plus efforts (null when the model advertises none). */
export interface ModelCost {
	input: number
	output: number
	cacheRead: number
	cacheWrite: number
}

export interface CatalogEntry {
	name: string
	context: number
	efforts: readonly string[] | null
	cost: ModelCost
	modalities: readonly InputModality[]
	/** Cheapest plan that serves the model; plans.md names this the access rule. */
	minPlan: string | null
}

export const CATALOG_VERSION = "1.65.2" as const

/** Every model the CLI table carried, keyed by the API's model id. */
export const MODEL_CATALOG: Readonly<Record<string, CatalogEntry>> = {
	"claude-fable-5": { name: "Claude Fable 5", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 }, modalities: ["text", "image"], minPlan: "Max" },
	"claude-fable-5-1": { name: "Claude Fable 5.1", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 10, output: 50, cacheRead: 0.25, cacheWrite: 12.5 }, modalities: ["text", "image"], minPlan: "Max" },
	"claude-haiku-4-5-20251001": { name: "Claude Haiku 4.5", context: 200000, efforts: null, cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 }, modalities: ["text", "image"], minPlan: "Pro" },
	"claude-opus-4-7": { name: "Claude Opus 4.7", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, modalities: ["text", "image"], minPlan: "Max" },
	"claude-opus-4-8": { name: "Claude Opus 4.8", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, modalities: ["text", "image"], minPlan: "Max" },
	"claude-opus-5": { name: "Claude Opus 5", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, modalities: ["text", "image"], minPlan: "Max" },
	"claude-opus-5-5": { name: "Claude Opus 5.5", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 4, output: 20, cacheRead: 0.2, cacheWrite: 5 }, modalities: ["text", "image"], minPlan: "Max" },
	"claude-sonnet-4-6": { name: "Claude Sonnet 4.6", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 }, modalities: ["text", "image"], minPlan: "Pro" },
	"claude-sonnet-5": { name: "Claude Sonnet 5", context: 1000000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 }, modalities: ["text", "image"], minPlan: "Pro" },
	"deepseek/deepseek-v4-flash": { name: "DeepSeek V4 Flash (latest)", context: 1000000, efforts: ["high","max"], cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"deepseek/deepseek-v4-flash-fast": { name: "DeepSeek V4 Flash Fast", context: 1000000, efforts: ["low","high","max"], cost: { input: 0.28, output: 0.56, cacheRead: 0.07, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"deepseek/deepseek-v4-flash-vision-exp": { name: "DeepSeek V4 Flash Vision (exp)", context: 1000000, efforts: ["high","max"], cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"deepseek/deepseek-v4-pro": { name: "DeepSeek V4 Pro (latest)", context: 1000000, efforts: ["high","max"], cost: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"deepseek/deepseek-v4.1-flash": { name: "DeepSeek V4.1 Flash", context: 1000000, efforts: ["low","high","max"], cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"google/gemini-3.1-flash-lite": { name: "Gemini 3.1 Flash Lite", context: 1000000, efforts: ["low","medium","high"], cost: { input: 0.25, output: 1.5, cacheRead: 0.03, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"google/gemini-3.5-flash": { name: "Gemini 3.5 Flash", context: 1000000, efforts: ["low","medium","high"], cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"google/gemini-3.5-flash-lite": { name: "Gemini 3.5 Flash Lite", context: 1000000, efforts: ["low","medium","high"], cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"google/gemini-3.6-flash": { name: "Gemini 3.6 Flash", context: 1000000, efforts: ["low","medium","high"], cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"google/gemini-3.7-flash": { name: "Gemini 3.7 Flash", context: 1050000, efforts: ["low","medium","high"], cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0.08334 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"google/gemini-3.8-flash": { name: "Gemini 3.8 Flash", context: 1000000, efforts: ["low","medium","high"], cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"gpt-5.3-codex": { name: "GPT-5.3 Codex", context: 400000, efforts: ["low","medium","high","xhigh"], cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"gpt-5.4": { name: "GPT-5.4", context: 400000, efforts: ["low","medium","high","xhigh"], cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"gpt-5.4-mini": { name: "GPT-5.4 Mini", context: 400000, efforts: ["low","medium","high"], cost: { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"gpt-5.5": { name: "GPT-5.5", context: 400000, efforts: ["low","medium","high","xhigh"], cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"gpt-5.6-luna": { name: "GPT-5.6 Luna", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 }, modalities: ["text", "image"], minPlan: "Go" },
	"gpt-5.6-sol": { name: "GPT-5.6 Sol", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"gpt-5.6-terra": { name: "GPT-5.6 Terra", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5 }, modalities: ["text", "image"], minPlan: "Pro" },
	"gpt-6-astra": { name: "GPT-6 Astra", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 }, modalities: ["text", "image"], minPlan: "Max" },
	"gpt-6-luna": { name: "GPT-6 Luna", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 0.1, output: 0.5, cacheRead: 0.01, cacheWrite: 0.125 }, modalities: ["text", "image"], minPlan: "Go" },
	"gpt-6-sol": { name: "GPT-6 Sol", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 }, modalities: ["text", "image"], minPlan: "Pro" },
	"inclusionai/ling-3.0-flash-sante:free": { name: "Ling 3.0 Flash Sante", context: 262000, efforts: null, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"meituan/LongCat-2.0": { name: "LongCat 2.0", context: 1050000, efforts: null, cost: { input: 0.3, output: 1.2, cacheRead: 0.006, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"meta/muse-spark-1.1": { name: "Muse Spark 1.1", context: 1050000, efforts: ["low","medium","high","xhigh"], cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Pro" },
	"meta/muse-spark-1.2": { name: "Muse Spark 1.2", context: 1050000, efforts: ["low","medium","high","xhigh"], cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"meta/muse-spark-1.2-contributor": { name: "Muse Spark 1.2 Contributor", context: 1050000, efforts: ["low","medium","high","xhigh"], cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"meta/muse-spark-1.3": { name: "Muse Spark 1.3", context: 1050000, efforts: ["low","medium","high","xhigh","max"], cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"meta/muse-spark-1.3-contributor": { name: "Muse Spark 1.3 Contributor", context: 1050000, efforts: ["low","medium","high","xhigh"], cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"MiniMaxAI/MiniMax-M2.5": { name: "MiniMax M2.5", context: 200000, efforts: null, cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"MiniMaxAI/MiniMax-M2.7": { name: "MiniMax M2.7", context: 0, efforts: null, cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"MiniMaxAI/MiniMax-M3": { name: "MiniMax M3", context: 1000000, efforts: ["low","medium","high"], cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"moonshotai/Kimi-K2.5": { name: "Kimi K2.5", context: 256000, efforts: null, cost: { input: 0.6, output: 3, cacheRead: 0.1, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"moonshotai/Kimi-K2.6": { name: "Kimi K2.6", context: 256000, efforts: null, cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"moonshotai/Kimi-K2.7-Code": { name: "Kimi K2.7 Code", context: 256000, efforts: null, cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"moonshotai/Kimi-K2.7-Code-Highspeed": { name: "Kimi K2.7 Code HighSpeed", context: 262000, efforts: null, cost: { input: 1.9, output: 8, cacheRead: 0.38, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"moonshotai/Kimi-K3": { name: "Kimi K3", context: 1000000, efforts: ["low","high","max"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"nvidia/nemotron-3-ultra-550b-a55b": { name: "Nemotron 3 Ultra", context: 1000000, efforts: null, cost: { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"poolside/laguna-s-2.1-free": { name: "Laguna S 2.1", context: 256000, efforts: null, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"Qwen/Qwen3.6-Max-Preview": { name: "Qwen 3.6 Max Preview", context: 0, efforts: null, cost: { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.63 }, modalities: ["text"], minPlan: "Go" },
	"Qwen/Qwen3.6-Plus": { name: "Qwen 3.6 Plus", context: 0, efforts: null, cost: { input: 0.5, output: 3, cacheRead: 0.1, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.7-Flash": { name: "Qwen 3.7 Flash", context: 1000000, efforts: null, cost: { input: 0.03, output: 0.13, cacheRead: 0.006, cacheWrite: 0.038 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.7-Max": { name: "Qwen 3.7 Max", context: 1000000, efforts: null, cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.13 }, modalities: ["text"], minPlan: "Go" },
	"Qwen/Qwen3.7-Plus": { name: "Qwen 3.7 Plus", context: 1000000, efforts: null, cost: { input: 0.4, output: 1.6, cacheRead: 0.08, cacheWrite: 0.5 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.8-27B": { name: "Qwen 3.8 27B", context: 262000, efforts: ["low","medium","xhigh"], cost: { input: 0.4, output: 3, cacheRead: 0.04, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.8-Flash": { name: "Qwen 3.8 Flash", context: 1000000, efforts: ["low","medium","xhigh"], cost: { input: 0.16, output: 0.47, cacheRead: 0.016, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.8-Max": { name: "Qwen 3.8 Max", context: 1000000, efforts: ["low","medium","xhigh"], cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.8-Max-0902": { name: "Qwen 3.8 Max 0902", context: 1000000, efforts: ["low","medium","xhigh"], cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"Qwen/Qwen3.8-Omni-Flash": { name: "Qwen 3.8 Omni Flash", context: 1000000, efforts: ["low","medium","xhigh"], cost: { input: 0.15, output: 0.47, cacheRead: 0.016, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"sakana/fugu-ultra": { name: "Fugu Ultra", context: 1000000, efforts: ["high","xhigh"], cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Max" },
	"stealth/space-bunny-alpha": { name: "Space Bunny Alpha", context: 1000000, efforts: ["low","medium","high"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"stepfun/Step-3.5-Flash": { name: "Step 3.5 Flash", context: 262000, efforts: null, cost: { input: 0.09, output: 0.3, cacheRead: 0.02, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"stepfun/Step-3.7-Flash": { name: "Step 3.7 Flash", context: 256000, efforts: null, cost: { input: 0.2, output: 1.15, cacheRead: 0.04, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"stepfun/Step-5-Preview": { name: "Step 5 Preview", context: 1000000, efforts: ["low","medium","high"], cost: { input: 1, output: 2.7, cacheRead: 0.05, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"tencent/hy3-paid": { name: "Tencent Hy3", context: 262000, efforts: null, cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"tencent/hy4-preview": { name: "Tencent Hy4 Preview", context: 1050000, efforts: ["low","medium","high"], cost: { input: 0.834, output: 2.501, cacheRead: 0.042, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"thinkingmachines/inkling": { name: "Inkling", context: 256000, efforts: null, cost: { input: 1, output: 4.05, cacheRead: 0.17, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"thinkingmachines/inkling-small": { name: "Inkling Small", context: 1000000, efforts: null, cost: { input: 0.5, output: 1.2, cacheRead: 0.1, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"xai/grok-4.5": { name: "Grok 4.5", context: 500000, efforts: ["low","medium","high"], cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"xai/grok-4.6": { name: "Grok 4.6", context: 500000, efforts: ["low","medium","high","xhigh"], cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"xai/grok-4.7": { name: "Grok 4.7", context: 500000, efforts: ["low","medium","high","xhigh"], cost: { input: 1.2, output: 3.6, cacheRead: 0.3, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"xiaomi/mimo-v2.5": { name: "MiMo V2.5", context: 1000000, efforts: null, cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"xiaomi/mimo-v2.5-pro": { name: "MiMo V2.5 Pro", context: 1000000, efforts: null, cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"xiaomi/mimo-v2.6-flash": { name: "MiMo V2.6 Flash", context: 1050000, efforts: null, cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"xiaomi/mimo-v2.6-pro": { name: "MiMo V2.6 Pro", context: 1050000, efforts: null, cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"xiaomi/mimo-v2.6-pro-ultraspeed": { name: "MiMo V2.6 Pro UltraSpeed", context: 1050000, efforts: null, cost: { input: 4.35, output: 8.7, cacheRead: 0.036, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "GOAT" },
	"z-ai/glm-5.3-flash": { name: "GLM-5.3 Flash", context: 1050000, efforts: ["low","high","max"], cost: { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"z-ai/glm-5.3-flashx": { name: "GLM-5.3 FlashX", context: 1000000, efforts: ["low","high","max"], cost: { input: 0.37, output: 1.25, cacheRead: 0.075, cacheWrite: 0 }, modalities: ["text", "image"], minPlan: "Go" },
	"zai-org/GLM-5": { name: "GLM-5", context: 200000, efforts: null, cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"zai-org/GLM-5.1": { name: "GLM-5.1", context: 0, efforts: null, cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"zai-org/GLM-5.2": { name: "GLM-5.2", context: 1000000, efforts: ["high","max"], cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"zai-org/GLM-5.2-Fast": { name: "GLM-5.2 Fast", context: 1000000, efforts: null, cost: { input: 3, output: 10.25, cacheRead: 0.5, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
	"zai-org/GLM-5.3": { name: "GLM-5.3", context: 1000000, efforts: ["low","high","max"], cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 }, modalities: ["text"], minPlan: "Go" },
}

/** Text-only default for any id this table does not list. */
export const TEXT_ONLY: readonly InputModality[] = ["text"]

export function inputModalities(id: string): readonly InputModality[] {
	return MODEL_CATALOG[id]?.modalities ?? TEXT_ONLY
}

export function supportsImage(id: string): boolean {
	return inputModalities(id).includes("image")
}

export function modelCost(id: string): ModelCost | undefined {
	return MODEL_CATALOG[id]?.cost
}

export function minPlan(id: string): string | null {
	return MODEL_CATALOG[id]?.minPlan ?? null
}

/** Reasoning-capable when it advertises explicit effort levels. */
export function isReasoningModel(id: string): boolean {
	const efforts = MODEL_CATALOG[id]?.efforts
	return Array.isArray(efforts) && efforts.length > 0
}

/** opencode effort variants for ctrl+t cycling. */
export function reasoningVariants(id: string): Record<string, { reasoningEffort: string }> | undefined {
	const efforts = MODEL_CATALOG[id]?.efforts
	if (!efforts || efforts.length === 0) return undefined
	return Object.fromEntries(efforts.map((effort) => [effort, { reasoningEffort: effort }]))
}
