// GENERATED by scripts/extract-modalities.ts — do not edit by hand.
// Source: command-code@1.65.0 (dist/cli.mjs). Regenerate with
// `bun scripts/extract-modalities.ts` after a Command Code model release.
//
// The listing API carries no capabilities, so this table is the only per-model
// source. Models absent here are text-only (OpenCode's default).

export type InputModality = "text" | "image" | "audio" | "video" | "pdf"

/** Models whose inputs go beyond text, keyed by the API's model id. */
export const MODEL_INPUT_MODALITIES: Readonly<Record<string, readonly InputModality[]>> = {
	"claude-fable-5": ["text", "image"],
	"claude-fable-5-1": ["text", "image"],
	"claude-haiku-4-5-20251001": ["text", "image"],
	"claude-opus-4-7": ["text", "image"],
	"claude-opus-4-8": ["text", "image"],
	"claude-opus-5": ["text", "image"],
	"claude-opus-5-5": ["text", "image"],
	"claude-sonnet-4-6": ["text", "image"],
	"claude-sonnet-5": ["text", "image"],
	"deepseek/deepseek-v4-flash-vision-exp": ["text", "image"],
	"deepseek/deepseek-v4.1-flash": ["text", "image"],
	"google/gemini-3.1-flash-lite": ["text", "image"],
	"google/gemini-3.5-flash": ["text", "image"],
	"google/gemini-3.5-flash-lite": ["text", "image"],
	"google/gemini-3.6-flash": ["text", "image"],
	"google/gemini-3.7-flash": ["text", "image"],
	"google/gemini-3.8-flash": ["text", "image"],
	"gpt-5.3-codex": ["text", "image"],
	"gpt-5.4": ["text", "image"],
	"gpt-5.4-mini": ["text", "image"],
	"gpt-5.5": ["text", "image"],
	"gpt-5.6-luna": ["text", "image"],
	"gpt-5.6-sol": ["text", "image"],
	"gpt-5.6-terra": ["text", "image"],
	"gpt-6-astra": ["text", "image"],
	"gpt-6-luna": ["text", "image"],
	"gpt-6-sol": ["text", "image"],
	"meta/muse-spark-1.1": ["text", "image"],
	"meta/muse-spark-1.2": ["text", "image"],
	"meta/muse-spark-1.2-contributor": ["text", "image"],
	"meta/muse-spark-1.3": ["text", "image"],
	"meta/muse-spark-1.3-contributor": ["text", "image"],
	"minimax/minimax-m3-free": ["text", "image"],
	"MiniMaxAI/MiniMax-M3": ["text", "image"],
	"moonshotai/Kimi-K2.5": ["text", "image"],
	"moonshotai/Kimi-K2.6": ["text", "image"],
	"moonshotai/Kimi-K2.7-Code": ["text", "image"],
	"moonshotai/Kimi-K2.7-Code-Highspeed": ["text", "image"],
	"moonshotai/Kimi-K3": ["text", "image"],
	"Qwen/Qwen3.6-Plus": ["text", "image"],
	"Qwen/Qwen3.7-Flash": ["text", "image"],
	"Qwen/Qwen3.7-Plus": ["text", "image"],
	"Qwen/Qwen3.8-27B": ["text", "image"],
	"Qwen/Qwen3.8-Flash": ["text", "image"],
	"Qwen/Qwen3.8-Max": ["text", "image"],
	"Qwen/Qwen3.8-Max-0902": ["text", "image"],
	"Qwen/Qwen3.8-Omni-Flash": ["text", "image"],
	"sakana/fugu-ultra": ["text", "image"],
	"stealth/space-bunny-alpha": ["text", "image"],
	"stepfun/Step-3.7-Flash": ["text", "image"],
	"stepfun/Step-5-Preview": ["text", "image"],
	"thinkingmachines/inkling": ["text", "image"],
	"thinkingmachines/inkling-small": ["text", "image"],
	"xai/grok-4.5": ["text", "image"],
	"xai/grok-4.6": ["text", "image"],
	"xai/grok-4.7": ["text", "image"],
	"xiaomi/mimo-v2.5": ["text", "image"],
	"xiaomi/mimo-v2.6-flash": ["text", "image"],
	"xiaomi/mimo-v2.6-pro": ["text", "image"],
	"xiaomi/mimo-v2.6-pro-ultraspeed": ["text", "image"],
	"z-ai/glm-5.3-flash": ["text", "image"],
	"z-ai/glm-5.3-flashx": ["text", "image"],
}

/** Text-only default for any id this table does not list. */
export const TEXT_ONLY: readonly InputModality[] = ["text"]

export function inputModalities(id: string): readonly InputModality[] {
	return MODEL_INPUT_MODALITIES[id] ?? TEXT_ONLY
}

export function supportsImage(id: string): boolean {
	return inputModalities(id).includes("image")
}
