// GENERATED by scripts/extract-gating.ts — do not edit by hand.
// Source: Command Code CLI bundle (plan-gating + model categories).
// Regen: bun run extract

export const OPEN_SOURCE = "opensource" as const;
export const PREMIUM = "premium" as const;
export type Category = "opensource" | "premium";

/** model id -> category (models absent from this table have unknown category) */
export const MODEL_CATEGORIES: Record<string, Category> = {
	"claude-sonnet-5": "premium",
	"claude-sonnet-4-6": "premium",
	"claude-fable-5": "premium",
	"claude-opus-5": "premium",
	"claude-opus-4-8": "premium",
	"claude-opus-4-7": "premium",
	"claude-haiku-4-5-20251001": "premium",
	"gpt-5.6-sol": "opensource",
	"gpt-5.6-terra": "premium",
	"gpt-5.6-luna": "opensource",
	"gpt-5.5": "premium",
	"gpt-5.4": "premium",
	"gpt-5.3-codex": "premium",
	"gpt-5.4-mini": "premium",
	"google/gemini-3.5-flash": "premium",
	"google/gemini-3.1-flash-lite": "premium",
	"sakana/fugu-ultra": "premium",
	"meta/muse-spark-1.1": "premium",
	"meta/muse-spark-1.2": "opensource",
	"meta/muse-spark-1.2-contributor": "opensource",
	"xai/grok-4.5": "opensource",
	"xai/grok-4.6": "opensource",
	"google/gemini-3.7-flash": "opensource",
	"z-ai/glm-5.3-flash": "opensource",
	"tencent/hy4-preview": "opensource",
	"tencent/hy3-paid": "opensource",
	"tencent/Hy3": "opensource",
	"MiniMaxAI/MiniMax-M3-Free": "opensource",
	"MiniMaxAI/MiniMax-M3": "opensource",
	"MiniMaxAI/MiniMax-M2.7": "opensource",
	"minimax/minimax-m3-free": "opensource",
	"minimax/minimax-m2.7-free": "opensource",
	"MiniMaxAI/MiniMax-M2.5": "opensource",
	"deepseek/deepseek-v4-pro": "opensource",
	"deepseek/deepseek-v4-flash": "opensource",
	"moonshotai/Kimi-K3": "opensource",
	"moonshotai/Kimi-K2.7-Code": "opensource",
	"moonshotai/Kimi-K2.7-Code-Highspeed": "opensource",
	"moonshotai/Kimi-K2.6": "opensource",
	"moonshotai/Kimi-K2.5": "opensource",
	"zai-org/GLM-5.3": "opensource",
	"zai-org/GLM-5.2": "opensource",
	"zai-org/GLM-5.2-Fast": "opensource",
	"zai-org/GLM-5.1": "opensource",
	"zai-org/GLM-5": "opensource",
	"xiaomi/mimo-v2.5-pro": "opensource",
	"xiaomi/mimo-v2.5": "opensource",
	"Qwen/Qwen3.6-Max-Preview": "opensource",
	"Qwen/Qwen3.6-Plus": "opensource",
	"Qwen/Qwen3.7-Max": "opensource",
	"Qwen/Qwen3.7-Plus": "opensource",
	"Qwen/Qwen3.8-Max": "opensource",
	"Qwen/Qwen3.8-27B": "opensource",
	"Qwen/Qwen3.8-Flash": "opensource",
	"Qwen/Qwen3.7-Flash": "opensource",
	"stepfun/Step-3.7-Flash": "opensource",
	"stepfun/Step-3.5-Flash": "opensource",
	"nvidia/nemotron-3-ultra-550b-a55b": "opensource",
	"thinkingmachines/inkling": "opensource",
};

/** planId -> access rules; plan ids absent from this table get everything */
export const PLAN_RULES: Record<
	string,
	{ allowedCategories: Category[]; blockedModels: string[] }
> = {
	"individual-go": {
		allowedCategories: ["opensource"],
		blockedModels: [
			"vercel-ai-gateway:meta/muse-spark-1.2",
			"vercel-ai-gateway:xai/grok-4.6",
			"openrouter:google/gemini-3.7-flash",
			"vercel-ai-gateway:gpt-5.6-sol",
		],
	},
	"individual-goat": {
		allowedCategories: ["opensource"],
		blockedModels: [],
	},
	"individual-pro": {
		allowedCategories: ["premium", "opensource"],
		blockedModels: [
			"anthropic:claude-fable-5",
			"anthropic:claude-opus-5",
			"anthropic:claude-opus-4-8",
			"anthropic:claude-opus-4-7",
			"anthropic:claude-opus-4-6",
			"anthropic:claude-opus-4-5-20251101",
			"vercel-ai-gateway:sakana/fugu-ultra",
		],
	},
	"individual-pro-v1": {
		allowedCategories: ["premium", "opensource"],
		blockedModels: [
			"anthropic:claude-fable-5",
			"anthropic:claude-opus-5",
			"anthropic:claude-opus-4-8",
			"anthropic:claude-opus-4-7",
			"anthropic:claude-opus-4-6",
			"anthropic:claude-opus-4-5-20251101",
			"vercel-ai-gateway:sakana/fugu-ultra",
		],
	},
	"individual-provider": {
		allowedCategories: ["premium", "opensource"],
		blockedModels: [],
	},
	"individual-max": {
		allowedCategories: ["premium", "opensource"],
		blockedModels: [],
	},
	"individual-ultra": {
		allowedCategories: ["premium", "opensource"],
		blockedModels: [],
	},
	"teams-pro": {
		allowedCategories: ["premium", "opensource"],
		blockedModels: [],
	},
};

/** canonical known model ids (lowercase compare) */
export const KNOWN_MODELS: string[] = [
	"claude-sonnet-4-6",
	"claude-fable-5",
	"claude-opus-5",
	"claude-opus-4-8",
	"claude-opus-4-7",
	"claude-haiku-4-5-20251001",
	"gpt-5.6-sol",
	"gpt-5.6-terra",
	"gpt-5.6-luna",
	"gpt-5.5",
	"gpt-5.4",
	"gpt-5.3-codex",
	"gpt-5.4-mini",
	"moonshotai/Kimi-K3",
	"thinkingmachines/inkling",
	"thinkingmachines/inkling-small",
	"deepseek/deepseek-v4-pro",
	"deepseek/deepseek-v4-flash",
	"deepseek/deepseek-v4-flash-vision-exp",
	"moonshotai/Kimi-K2.7-Code",
	"moonshotai/Kimi-K2.7-Code-Highspeed",
	"moonshotai/Kimi-K2.6",
	"moonshotai/Kimi-K2.5",
	"zai-org/GLM-5.3",
	"z-ai/glm-5.3-flash",
	"zai-org/GLM-5.2",
	"zai-org/GLM-5.2-Fast",
	"zai-org/GLM-5.1",
	"zai-org/GLM-5",
	"xiaomi/mimo-v2.5-pro",
	"xiaomi/mimo-v2.5",
	"stepfun/Step-3.7-Flash",
	"stepfun/Step-3.5-Flash",
	"tencent/hy4-preview",
	"tencent/hy3-paid",
	"tencent/Hy3",
	"google/gemini-3.7-flash",
	"google/gemini-3.6-flash",
	"google/gemini-3.5-flash",
	"google/gemini-3.5-flash-lite",
	"google/gemini-3.1-flash-lite",
	"sakana/fugu-ultra",
	"xai/grok-4.5",
	"xai/grok-4.6",
	"meta/muse-spark-1.1",
	"meta/muse-spark-1.2",
	"meta/muse-spark-1.2-contributor",
	"nvidia/nemotron-3-ultra-550b-a55b",
	"poolside/laguna-s-2.1-free",
	"inclusionai/ling-3.0-flash-free",
	"minimax/minimax-m3-free",
	"minimax/minimax-m2.7-free",
	"claude-sonnet-5",
	"MiniMaxAI/MiniMax-M3-Free",
	"MiniMaxAI/MiniMax-M3",
	"MiniMaxAI/MiniMax-M2.7",
	"MiniMaxAI/MiniMax-M2.5",
	"Qwen/Qwen3.6-Max-Preview",
	"Qwen/Qwen3.6-Plus",
	"Qwen/Qwen3.7-Max",
	"Qwen/Qwen3.7-Plus",
	"Qwen/Qwen3.8-Max",
	"Qwen/Qwen3.8-27B",
	"Qwen/Qwen3.8-Flash",
	"Qwen/Qwen3.7-Flash",
];

/** deprecated/aliased model id -> canonical id */
export const MODEL_ALIASES: Record<string, string> = {
	"claude-sonnet-4-20250514": "claude-sonnet-4-6",
	"claude-sonnet-4-5-20250929": "claude-sonnet-4-6",
	"claude-opus-4-5-20251101": "claude-opus-4-7",
	"claude-opus-4-6": "claude-opus-4-7",
	"claude-haiku-4-5": "claude-haiku-4-5-20251001",
};

/** strip a trailing date suffix like -20251101 before aliasing (mirrors CLI kr regex) */
function findKnown(s: string): string | undefined {
	const k = s.toLowerCase();
	return KNOWN_MODELS.find((m) => m.toLowerCase() === k);
}

export function canonicalizeModelId(model: string): string {
	const stripDate = (s: string) => s.replace(/[-@]\d{8}$/, "");
	const direct = findKnown(model);
	if (direct) return direct;
	const aliased = MODEL_ALIASES[model.toLowerCase()];
	if (aliased) return findKnown(aliased) ?? model;
	return findKnown(stripDate(model)) ?? model;
}
